### ISSUE TITLE
direct.h missing?

### ISSUE THREAD

**Issue by 192933488S** [QuantumLeaps/qtools#1]
Hi Miro,
I'm try building qclean using MSYS2.

```
C:\dev\qtools-master\qclean\win32>gcc -O2 -c -Wall -Wextra -I..\include -orel\filesearch.o filesearch.c
filesearch.c:43:20: schwerwiegender Fehler: direct.h: No such file or directory
 #include <direct.h>
                    ^
Kompilierung beendet.

```
direct.h is not part of qtools-master.

[Stackoverflow related: Cannot find direct.h](https://stackoverflow.com/questions/6193607/cannot-find-direct-h)

You also say "QCLEAN is pre-compiled and ready to use on Windows and Linux/Unix.
Source code is also provided." but I cannot find the executable.

Thanks

**Comment by quantum-leaps** [comment]
Hi Ludwig,
Thank you for your interest in QTools.

The binaries of all utilities, including of course qclean, are included in the QTools releases. You can get the pre-built release by clicking on the "release" link at the top of the QTools repository. The direct link to releases is [here](https://github.com/QuantumLeaps/qtools/releases).

Regarding your compilation errors, I'm not sure why you are getting this. But once you have QTools (the binary release) installed on your machine, you should be able to simply use the MinGW compiler that is included with QTools. All you need to do is to add the qtools\bin directory to your PATH environment variable. All of this is described in the README.md file for QTools.

--MMS

**Comment by 192933488S** [comment]
Got it and it's working nicely. I must have downloaded the repo instead of the actual release, so there the binary is of course. -LS
