### ISSUE TITLE
Add Support for Target Link via UDP

### ISSUE THREAD

**Issue by DanielLyubin** [QuantumLeaps/qtools#12]
Currently QSpy supports target link via serial communication, TCP and file input. I need QSpy to enable receiving output from target via UDP. I don't have implementation for TCP on target so I need to send QSpy output via UDP.

Also, is QSpy able to bind ip addresses other than localhost? Does it rely on port only?

**Comment by quantum-leaps** [comment]
Hi Daniel,
There are currently no plans to add UDP as input channel to QSPY (or as output channel to QS ports). If you need something like that, you can try to modify the QSPY source code, which is freely available. Specifically, UDP is already used to communicate with the QUTest and QView "front-ends", so you can see the code that's needed.

Regarding the host names/IP addresses/port numbers, all of this is fully configurable via [QSPY command-line options](https://www.state-machine.com/qtools/qspy.html#qspy_command). Specifically, the option `-t` takes an optional [TCP-port] parameter, which is the port number. You might also watch a video that shows how to work with QSPY remotely, where an embedded-linux target (Raspberry PI) talks to QSPY running on a host (Windows), see:

https://youtu.be/0AaPRMSt2jg

-MMS
