### ISSUE TITLE
Qutest in pypi still not updated to 7.2.0

### ISSUE THREAD

**Issue by gbThreepwood** [QuantumLeaps/qtools#16]
The qutest version available in pypi is still at versjon 7.1.2 (although a pre-release for 7.2.0 is available): https://pypi.org/project/qutest/#history

This caused some confusion for me as "assertion" tests where failing with qspy at version 7.2.1, and I did not realize that I had an older version of qutest.

The failure message in qutest is:
exp: end-of-test
got: "" (timeout)

**Comment by quantum-leaps** [comment]
The project [qutest has been updated on PyPi](https://pypi.org/project/qutest).
This issue is then closed.
--MMS
