### ISSUE TITLE
cmake support for `qtools`

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qtools#18]
Hi Miro,
the attached [zip archive](https://github.com/QuantumLeaps/qtools/files/14448572/qtools_diff.zip)
 adds `CMakeLists.txt` files to
- `qclean`
- `qfsgen`
- `qspy` and
- the `qtools`root directory
The distinction between `win32` and `posix` is done automatically based on CMake variables describing the system (`MSYS`, `UNIX` or `CMAKE_SYSTEM_NAME` having a value of `Linux`, `Darwin` or `MSYS`).

With this you can build the tools independently by using cmake in the tool's directory like this:
`cmake -B<Build Dir> && cmake --build <Build Dir>`
e.g. (in qtools/qspy) - `cmake -Bbuild && cmake --build build`. This will build `qspy` in the directory `.../qtools/qspy/build`.
Or you can build all tools (qclean, qfsgen, qspy) at once from the `qtools`directory with exactly the same command line as above. 
This will build the tools in `build/qclean`, `build/qfsgen` and `build/qspy`.

**Comment by stefanschober** [comment]
sorry, I missed to update a description.
Please apply this diff to the `CMakeLists.txt` in `qtools`:
```
--- CMakeLists.txt.o    2024-02-29 14:27:28.891856600 +0100
+++ CMakeLists.txt      2024-02-29 14:27:50.692035300 +0100
@@ -24,7 +24,7 @@
 project(
     qtools
     VERSION ${SW_VERSION}
-    DESCRIPTION "QTools qspy - https://www.state-machine.com/qtools/qspy.html"
+    DESCRIPTION "QTools - https://www.state-machine.com/qtools/"
     LANGUAGES C
 )
```

**Comment by quantum-leaps** [comment]
Done.
--MMS

**Comment by quantum-leaps** [comment]
Done.
--MMS

**Comment by stefanschober** [comment]
That's quick :-)
Thanks
closed...
