### ISSUE TITLE
Use Tkinter frame object for custom GUI in QView

### ISSUE THREAD

**Issue by sulemankm** [QuantumLeaps/qtools#19]
Hi,  Currently QView supports a Tkinter Canvas object for provided custom application-specific UI in QView.  It would be nice if we could instead use a Tkinter Frame object instead of a canvas.  The frame object could use various layout managers, built-in tkinter widgets and even an embedded canvas (if required) to display custom UI.

**Comment by quantum-leaps** [comment]
The requested Tkinter frame has been added to QView (in the View|Frame menu). The [qview.py](https://github.com/QuantumLeaps/qtools/blob/main/qview/qview.py) script with this feature is in the QTools repository. Please try it and post here how you like it.
--MMS

**Comment by sulemankm** [comment]
Hi, thanks for the quick response.  The qview code look fine, but jus wondering, do we need to add a show_frame() method as is available for canvas ie show_canvas() to be called from the Customiztion class's constructor?

But aside from that, the idea that qview should hard-code a canvas or frame object may be reviewed.  Instead qview can ask the customization class to return the main gui object eg canvas or frame etc and then qview can manage that gui object.  As I understand, qview only needs to show and hide this gui object.

This would probably be a more flexible approach for customization.

**Comment by quantum-leaps** [comment]
The function show_frame() has been added. Thank you for catching this.

Regarding the suggestion about a more flexible approach to let customizations add a drawing object, it has merits. The main problem is, as always, backward compatibility. The changes should not break existing customization scripts.
