### ISSUE TITLE
cmake updates to qtools

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qtools#20]
cmake updates to...
... build centrally from the qtools directory. The separate build may be selected via the --target <build target> command line option to cmake
... install targets were added to help installing the binaries and accompanying files in an appropriate manner
... Readme.md updated with a cmake related section

@Miro: please have a look at Readme.md, if the explanations fit into the environment - Thanks - 
[qtools-update.zip](https://github.com/QuantumLeaps/qtools/files/14624711/qtools-update.zip)

**Comment by stefanschober** [comment]
Sorry, my mistake. For some reason, the zip archive is empty. I'll be back with the real diff asap.

**Comment by stefanschober** [comment]
reopened with working diff
[qtools_diff.zip](https://github.com/QuantumLeaps/qtools/files/14647502/qtools_diff.zip)

**Comment by quantum-leaps** [comment]
Done.
(Again some "whitespace errors" in README.md).
--MMS
