### ISSUE TITLE
Typo fixed in qtools/CMakeLists.txt

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qtools#21]
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3ea7bf6..6015f54 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -62,7 +62,7 @@ list(APPEND QBIN Termite.ini)
 list(TRANSFORM QBIN PREPEND bin/)
 
 install(TARGETS ${QTARGETS})
-install(PROGRAMS ${BIN_FILES} TYPE BIN)
+install(PROGRAMS ${QBIN} TYPE BIN)
 install(DIRECTORY doc LICENSES DESTINATION ${QDATAROOT}/doc)
 install(FILES README.md DESTINATION ${QDATAROOT}/doc)
 install(DIRECTORY ${QDIRS} DESTINATION ${QD

**Comment by quantum-leaps** [comment]
Done and checked in.
Thanks a lot,
--MMS
