### ISSUE TITLE
Is it support linux?

### ISSUE THREAD

**Issue by zhangshengping** [QuantumLeaps/qtools#8]
I want to use it on Ubuntu 18. How to install it?

**Comment by quantum-leaps** [comment]
Yes, you can use QTools on Linux (as well as Windows and MacOS). The procedure of downloading, installing and getting started with QTools is available in the online documentation at:

https://www.state-machine.com/qtools/start.html

There is also a [support forum](https://sourceforge.net/p/qpc/discussion/668726), where you can find answers to many questions and you can ask for support. Specifically to using QTools on Linux, there is a relevant discussion at:

https://sourceforge.net/p/qpc/discussion/668726/thread/ee29181333/

--Miro
